name: meditation_app
description: "MVVM based meditation app"
publish_to: 'none'
version: 1.0.1+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/svg/
    - assets/fonts/

  fonts:
    - family: SFDisplay
      fonts:
        - asset: assets/fonts/sf_pro_display.otf
          weight: 600
